### ISSUE TITLE
Have you measured memory usage during the time?

### ISSUE THREAD

**Issue by actionless** [Airblader/unclutter-xfixes#9]
After running for about 4-5 days it grew from 

```
%CPU %MEM    VSZ   RSS
0.0  0.0  27424  1400
```
to
```
0.0  3.4 270300 243640
```

i haven't did more precise measurements, but imho that's enough already for reporting.

**Comment by Airblader** [comment]
I've just run it under valgrind for a while. The only memory leaks it found were memory leaks in libev, so I'm inclined to say this isn't a bug within unclutter-xfixes. But maybe your valgrind says something else?

````
valgrind --leak-check=full unclutter # … and any other options you usually set
```

**Comment by Airblader** [comment]
Actually I think there might indeed be a bug on our side here. I'm looking into it.

**Comment by Airblader** [comment]
@actionless Fixed now, thanks for the report!

**Comment by actionless** [comment]
after this patch it fails to start, here is strace: http://sprunge.us/CEHg

**Comment by Airblader** [comment]
@actionless You were a little too fast. :-) I had pushed another commit which caused a segfault. I've reverted that one again already. I assume that's what you saw, your link doesn't work for me.

**Comment by actionless** [comment]
ok, thanks, i'll check it's memory isage in few days

**Comment by Airblader** [comment]
That'd be great to confirm it's fixed, thanks!

**Comment by Airblader** [comment]
@actionless Given that there's not much development going on and we now have a crucial bugfix, I think once I get your confirmation on it I am also going to push out a new release so the fix propagates.

**Comment by Airblader** [comment]
@actionless So, what's the status?

**Comment by actionless** [comment]
up 11.5 h
```
%MEM    VSZ   RSS
 0.0  27424  1372
```

**Comment by Airblader** [comment]
@actionless Thanks, I've released v1.1 now.

**Comment by actionless** [comment]
after 13 more hours it's still the same, thanks for the fix!
